/**
 * Serialising a result to disk, shared by `inspect --out` and the wizard.
 *
 * Two formats. JSON is the interchange format — feed it to a load test, a
 * notebook, anything that speaks JSON. The TypeScript module is for fixtures
 * you import: it carries the row type, so a fixture that drifts from the
 * schema fails at `tsc` rather than at render time.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

import type { QueryResult } from '#/lib/gen/query.ts'

export type OutputFormat = 'json' | 'ts'

export type Dataset = QueryResult['meta']['dataset']

/** Row type exported by `schema.ts` for each dataset. */
const ROW_TYPES: Record<Dataset, string> = {
  readings: 'Reading',
  risk: 'RiskDay',
  'work-orders': 'WorkOrder',
  units: 'Unit',
  buildings: 'Building',
}

export interface WriteOptions {
  format: OutputFormat
  /** Identifier for the `ts` format. Ignored for `json`. */
  exportName?: string
  pretty: boolean
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

const RESERVED = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
])

/** `null` when valid, otherwise the reason it is not. */
export function validateExportName(name: string): string | null {
  if (!name.trim()) return 'Required'
  if (!IDENTIFIER.test(name)) {
    return 'Must be a valid identifier — letters, digits, _ or $, not starting with a digit'
  }
  if (RESERVED.has(name)) return `"${name}" is a reserved word`
  return null
}

/** `risk` → `riskFixture`, `work-orders` → `workOrdersFixture`. */
export function defaultExportName(dataset: Dataset): string {
  const camel = dataset.replace(/-(.)/g, (_, char: string) =>
    char.toUpperCase(),
  )
  return `${camel}Fixture`
}

export function defaultFileName(
  dataset: Dataset,
  format: OutputFormat,
): string {
  return `${dataset}.${format}`
}

/**
 * A `ts` fixture has to live under `src/` for the `#/*` import to resolve;
 * JSON has no such constraint.
 */
export function defaultDirectory(format: OutputFormat): string {
  return format === 'ts' ? 'src/fixtures' : 'fixtures'
}

function tsModule(
  result: QueryResult,
  exportName: string,
  pretty: boolean,
): string {
  const { meta } = result
  const rowType = ROW_TYPES[meta.dataset]
  const rows = pretty
    ? JSON.stringify(result.rows, null, 2)
    : JSON.stringify(result.rows)

  return `/**
 * Generated by \`damp\` — do not edit.
 *
 * ${meta.dataset} · ${meta.from} → ${meta.to} · ${meta.resolution}
 * seed ${meta.seed} · ${meta.count.toLocaleString()} rows
 *
 * Regenerate with the same seed and window to reproduce this file exactly.
 */

import type { ${rowType} } from '#/lib/gen/schema.ts'

export const ${exportName}: Array<${rowType}> = ${rows}
`
}

function serialise(result: QueryResult, options: WriteOptions): string {
  if (options.format === 'ts') {
    const name = options.exportName ?? defaultExportName(result.meta.dataset)
    return tsModule(result, name, options.pretty)
  }
  return options.pretty
    ? JSON.stringify(result, null, 2)
    : JSON.stringify(result)
}

/**
 * Write the result to disk, creating parent directories.
 *
 * `json` carries rows and meta; `ts` carries rows only, with meta in the
 * header comment — a fixture you import should be the data, not a wrapper.
 */
export function writeResult(
  result: QueryResult,
  path: string,
  options: WriteOptions,
): { path: string; bytes: number } {
  const target = resolve(path)
  mkdirSync(dirname(target), { recursive: true })
  const body = serialise(result, options)
  writeFileSync(target, body)
  return { path: target, bytes: Buffer.byteLength(body) }
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  const units = ['kB', 'MB', 'GB']
  let value = bytes / 1024
  let unit = 0
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit++
  }
  return `${value.toFixed(1)} ${units[unit]}`
}
